FROM elixir:1.17 AS builder

WORKDIR /app
ENV MIX_ENV=prod

COPY mix.exs mix.ex[s] mix.loc[k] ./
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get --only prod

COPY lib ./lib
COPY config ./config

RUN mix compile && mix release

# Runtime — тот же образ что и builder, OpenSSL гарантированно совместим
FROM elixir:1.17

RUN mkdir -p /etc/tspu_x

COPY --from=builder /app/_build/prod/rel/tspu_x ./release

EXPOSE 4040 4043
CMD ["./release/bin/tspu_x", "start"]
